// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/movies/service.proto

package movies

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchTerm struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year                 int32    `protobuf:"varint,2,opt,name=Year,proto3" json:"Year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTerm) Reset()         { *m = SearchTerm{} }
func (m *SearchTerm) String() string { return proto.CompactTextString(m) }
func (*SearchTerm) ProtoMessage()    {}
func (*SearchTerm) Descriptor() ([]byte, []int) {
	return fileDescriptor_b51b5648ec9e56c5, []int{0}
}

func (m *SearchTerm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTerm.Unmarshal(m, b)
}
func (m *SearchTerm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTerm.Marshal(b, m, deterministic)
}
func (m *SearchTerm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTerm.Merge(m, src)
}
func (m *SearchTerm) XXX_Size() int {
	return xxx_messageInfo_SearchTerm.Size(m)
}
func (m *SearchTerm) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTerm.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTerm proto.InternalMessageInfo

func (m *SearchTerm) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchTerm) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type Item struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year                 int32    `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Plot                 string   `protobuf:"bytes,3,opt,name=plot,proto3" json:"plot,omitempty"`
	Rating               float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_b51b5648ec9e56c5, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Item) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

func (m *Item) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchTerm)(nil), "com.moz5691.twirp.movies.SearchTerm")
	proto.RegisterType((*Item)(nil), "com.moz5691.twirp.movies.Item")
}

func init() { proto.RegisterFile("rpc/movies/service.proto", fileDescriptor_b51b5648ec9e56c5) }

var fileDescriptor_b51b5648ec9e56c5 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x2a, 0x48, 0xd6,
	0xcf, 0xcd, 0x2f, 0xcb, 0x4c, 0x2d, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xce, 0xcf, 0xd5, 0xcb, 0xcd, 0xaf, 0x32, 0x35, 0xb3,
	0x34, 0xd4, 0x2b, 0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0x83, 0xa8, 0x53, 0x32, 0xe3, 0xe2, 0x0a, 0x4e,
	0x4d, 0x2c, 0x4a, 0xce, 0x08, 0x49, 0x2d, 0xca, 0x15, 0x12, 0xe1, 0x62, 0x0d, 0xc9, 0x2c, 0xc9,
	0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x22, 0x53,
	0x13, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0xa5, 0x18, 0x2e, 0x16, 0xcf,
	0x92, 0x54, 0xb0, 0x8e, 0x12, 0x64, 0x1d, 0x25, 0x30, 0x1d, 0x95, 0x48, 0x3a, 0x40, 0x6c, 0x90,
	0x58, 0x41, 0x4e, 0x7e, 0x89, 0x04, 0x33, 0x58, 0x21, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x56, 0x94,
	0x58, 0x92, 0x99, 0x97, 0x2e, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x14, 0x04, 0xe5, 0x19, 0x9d, 0x66,
	0xe2, 0x62, 0xf3, 0x05, 0x3b, 0x50, 0x28, 0x88, 0x8b, 0xcb, 0x3d, 0xb5, 0xc4, 0xa9, 0x12, 0xe2,
	0x14, 0x15, 0x3d, 0x5c, 0x3e, 0xd1, 0x43, 0x78, 0x43, 0x4a, 0x0e, 0xb7, 0x2a, 0xb0, 0xa3, 0xa3,
	0xb9, 0x78, 0x5d, 0x52, 0x73, 0x52, 0x4b, 0x52, 0x49, 0x33, 0x96, 0x28, 0x55, 0x42, 0x1e, 0x5c,
	0x6c, 0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x42, 0x04, 0x9c, 0x41, 0xd0, 0x99, 0x6e, 0x5c, 0x2c,
	0x01, 0xf9, 0xc5, 0x25, 0x94, 0x9a, 0xe3, 0xc4, 0x11, 0xc5, 0x06, 0xe1, 0x26, 0xb1, 0x81, 0x93,
	0x83, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xbe, 0xfd, 0xa1, 0x2a, 0x02, 0x00, 0x00,
}
